project:
  type: website
  output-dir: docs

website:
  title: "Riley Calbow's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: rcalbow-portfolio.qmd
        text: "Project"

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

