project:
  type: website
  output-dir: docs

website:
  title: "r-calbow-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Portfolio

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

