---
title: "Cleaner nMDS Plots"
author: "Otto Martinez"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(vegan)
library(multcompView)
```

load in algae and do the main group condensing
```{r load in and clean up algae}
#load in data with read_csv and name it
algae <- read_csv("Data/Algae_Forreal_3.csv")

#unique shows the indiviudal data names for the "Site" column
unique(algae$Site)

#str tells if columns are character or numerical data
str(algae)
# we see kelp is a chr, kelp is a chr, this is weird
  #change character to numerical with the code below
algae$Kelp <- as.numeric(algae$Kelp)
which(is.na(algae$Kelp)) #this gets rid of any N/A rows of data

#make site names consistent

#telling R, when you see "X", change it to "Y"
        ## mutate(Site = replace(Site, Sitee == "X", "Y"))
algae2 <- algae %>%
  mutate(Site = replace(Site, Site == "Pescadero Point", "Pescadero")) %>%
  mutate(Site = replace(Site, Site == "Carmel Pt.", "Carmel Point")) %>% 
  mutate(Site = replace(Site, Site == "Pt Pinos", "Point Pinos")) %>% 
  mutate(Year = replace(Year, Year == "20230831", "2023")) %>% 
  filter(Site != "Point Lobos", Site != "Sea Palm", Site != "Soberanes")

#condensing
  #grouping corralines together
wsncond <- algae2 %>% 
  #mutate creates a new column; for example, I'm adding the values from all the inveretbebrates columns into a new column "OI" (other inverts)
  mutate(OI = Anem+Barn+Other, Encrusting = CrNC+CrCor+AC, Kelp = SG+Kelp, Macrophytes = Cort+Leath) %>% 
  rename("Mussels" = "Mussel") %>% 
  #get rid of any columns with data I don't need
  select(-c( "Lat_Start", "Long_Start", "Lat_End", "Long_End", "Side", "Quad", "Anem", "Barn", "Other", "CrNC", "CrCor", "SG", "Cort", "Leath", "AC")) %>% 
  #and then get rid of any rows of data with N/A's
  drop_na()

#now the following codes are similar but I was experimenting with which way of condensing the functional groups might show the best changes on the nMDS plots

#condensing #2
  #corralines separate
wsncond2 <- algae2 %>% 
  mutate("Other Invertebrates" = Anem+Barn+Other, "Crst Cor" = CrCor, "Crst NonCor" = CrNC, "Artc Cor" = AC, Kelp = SG+Kelp, Macrophytes = Cort+Leath) %>% 
  rename("Mussels" = "Mussel", "Bare Rock" = "BR") %>% 
  select(-c( "Lat_Start", "Long_Start", "Lat_End", "Long_End", "Side", "Quad", "Anem", "Barn", "Other", "CrNC", "CrCor", "SG", "Cort", "Leath", "AC")) %>% 
  drop_na()

#condense #3
  #articulated separate but crustings together; created macrophyte group (used for individual sites)
wsncond3 <- algae2 %>% 
  mutate("Other Invertebrates" = Anem+Barn+Other, "Encrusting" = CrCor+CrNC, "Artc Cor" = AC, Kelp = SG+Kelp, Macrophytes = Cort+Leath) %>% 
  rename("Mussels" = "Mussel", "Bare Rock" = "BR") %>% 
  select(-c( "Lat_Start", "Long_Start", "Lat_End", "Long_End", "Side", "Quad", "Anem", "Barn", "Other", "CrNC", "CrCor", "SG", "Cort", "Leath", "AC")) %>% 
  drop_na()

#condense #4
  #same as above but kept corticated and leathery separate (used for big plot)
wsncond4 <- algae2 %>% 
  mutate("Other Invertebrates" = Anem+Barn+Other, "Crst Cor" = CrCor, "Crst NonCor" = CrNC, "Artc Cor" = AC, Kelp = SG+Kelp, "Corticated"= Cort, "Leathery" = Leath) %>% 
  rename("Mussels" = "Mussel", "Bare Rock" = "BR") %>% 
  select(-c( "Lat_Start", "Long_Start", "Lat_End", "Long_End", "Side", "Quad", "Anem", "Barn", "Other", "CrNC", "CrCor", "SG", "AC", "Leath", "Cort")) %>% 
  drop_na()


#transect averages #1
travg_wsn <- wsncond %>% 
  group_by(Site, Year, Season, Transect) %>% 
  filter( Season == "Summer") %>% 
  drop_na() %>% 
  summarise( "Bare Rock" = mean(BR), Filamentous=mean(Fila), Encrusting=mean(Encrusting), Kelp=mean(Kelp), "Other Inverts" = mean(OI), Macrophytes=mean(Macrophytes), Mussels=mean(Mussels), Foliose=mean(Foliose)) %>% 
  ungroup() %>% 
  select(-c("Season", "Transect"))

#then I got the averages of all 5 quadrats for each transect

#transect avg #2
travg_wsn2 <- wsncond4 %>% 
  #idk the best way to describe what group_by does, but it basically keeps certain columns together for later in the chunk when preforming the "summarise" function
  group_by(Site, Year, Season, Transect) %>% 
  #we only need the data from summer so get rid of any winter and fall data. although looking back at the data, i believe in one of the earlier codes the "drop_na()" got rid of the other seasons since data for the other seasons had N/A's for the transects
  filter(Season == "Summer") %>% 
  #then we get the averages for our data
  summarise_all(mean) %>% 
  #then i ungroup the columns so I can go back in and get rid of the "Season" and "Transect" columns since that data doesn't need to be put on the graphs
  ungroup() %>% 
  select(-c("Season", "Transect"))

#transect avg #3
travg_wsn3 <- wsncond3 %>% 
  group_by(Site, Year, Season, Transect) %>% 
  filter(Season == "Summer") %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  select(-c("Season", "Transect"))

#then I took the averages for every quadrat at a site for each year
wsn_all_avg <- wsncond %>% 
  #the order is switched up here cause since I don't need to group by season or transect so I could get rid of them before grouping.
  select(-c("Season", "Transect")) %>% 
  group_by(Site, Year) %>% 
  #here I was dumb and did a really long line of "summarise()" and did the averages for each column. Like the other chunks above and below, it would be easier to just use the "summarise_all()" function so you don't have to type out each calculation
  summarise( "Bare Rock" = mean(BR), Filamentous=mean(Fila), Encrusting=mean(Encrusting), Kelp=mean(Kelp), "Other Inverts" = mean(OI), Macrophytes=mean(Macrophytes), Mussels=mean(Mussels), Foliose=mean(Foliose))

#doing that for condensing #2
wsn_all_avg2 <- wsncond4 %>% 
  select(-c("Season", "Transect")) %>% 
  group_by(Site, Year) %>% 
  summarise_all(mean)
```

time for 50 billion nmds plots
```{r everything}
#so basically performing nMDS's are pretty simple once you understand the first set, and then it's a plug and chug for every other nMDS you run

#star by creating a data matrix from your data table
  #assign a new name to the data table you're performing the nMDS on
wsnall_matr <- wsn_all_avg

#we're gonna come back to these steps later, but create a value that's just the "Site" data. This will be pasted back on the nMDS results. We'll take the values from the original data set and not the matrix
waavg_site <- wsn_all_avg$Site
#to the matrix we made initially, remove the "Site" Column since the nMDS can only be performed on a matrix with just numerical values
wsnall_matr$Site <- NULL

#do the same as two steps as above but to for the "Year" column
waavg_yr <- wsn_all_avg$Year
wsnall_matr$Year <- NULL

#now we actually perform the nMDS.Create name for the nMDS and then use the "metaMDS()" function using the matrix you created in the first step. "trymax" is used to set the upper limits for how many times R will do the calculations to try and find the best fit.
waavg_nmds <- metaMDS(wsnall_matr, trymax = 200)
waavg

#Ok so this whole section below is weird to explain but I'll try my best

#since the nMDS we created is in R as a list, we have to convert it to a data frame. Create a new data table (in all of these, "dscr" refers to data scores since we're making a table of all the scores from the nMDS) and use the following code, just plug in whatever name you have for the nMDS you created above. One thing that is confusing is that in the code below, "sites" refers to something within the nMDS and is NOT "Sites" as in the the survey sites.
waavg_dscr <- as.data.frame(scores(waavg_nmds)$sites)

#allows you to give names to the rows of data. This will allow us to stitch the "Year" and "Site" values back on to the data table. In the following code, Samp is the name we're giving to a new column we're creating so we can stitch those values back on.
waavg_dscr$Samp <- rownames(waavg_dscr)

#Create a column called "Site" where we'll add the "Site" values back from earlier. Now each pair of X and Y data points in the nMDS table will have the survey site it was obtained from added back to it. 
waavg_dscr$Site <- waavg_site
#Then we want to change the data to a factor
waavg_dscr$Site <- as.factor(waavg_dscr$Site)

#Do the same as above but for "Year"
waavg_dscr$Year <- waavg_yr
waavg_dscr$Year <- as.factor(waavg_dscr$Year)

#the final step here is to create the other data table where in the graphs it shows the the text for the variables (functional groups). 
waavg_spscr <- as.data.frame(scores(waavg_nmds, "species"))
waavg_spscr$species <- rownames(waavg_spscr)

#now graph it's graphing time
waavg_plot <- ggplot() +
  #we start with the geom_text layer so the graph plots out our variables. this will help visualise what each quadrar/site is dominated by. regardless of what you're plotting, everything in the "aes" is the same as below. Alpha controls opacity.
  geom_text(data = waavg_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  #then the geom_point layer to plot out the data points.
  geom_point(data = waavg_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Site), size = 6.75, alpha = .8) +
  #color time!! you can look up "ggplot colors" online to see the full array of colors you can get in ggplot
  scale_color_manual(values = c("firebrick2", "gold", "darkorange",  "chartreuse3", "dodgerblue", "purple3"))+
  #same goes for shapes. you can look up all the shapes in ggplot and then in the c() you select the number correlated to the shape you want
  scale_shape_manual(values = c(18, 18, 19)) +
  #and then when it comes to theme stuff, i recomend playing around with everything to see what formating looks best for you
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

#and then look at your beautiful creation
waavg_plot

#this is how u save graphs as images on your computer. note that it will save the last generated graph in the whole R markdown and not the one in the code chunk. So make sure you visualise the graph you want to save before running this code
ggsave(file = "waavg_plot.png", width = 8, height = 6)
```

now pretty much everything below is just plugging and chugging with different sites, averages combos, etc.

```{r everything 2}
wsnall_matr2 <- wsn_all_avg2

waavg_site2 <- wsn_all_avg2$Site
wsnall_matr2$Site <- NULL

waavg_yr2 <- wsn_all_avg2$Year
wsnall_matr2$Year <- NULL

waavg_nmds2 <- metaMDS(wsnall_matr2, trymax = 200)
waavg_nmds2

waavg_dscr2 <- as.data.frame(scores(waavg_nmds2)$sites)

waavg_dscr2$Samp <- rownames(waavg_dscr2)

waavg_dscr2$Site <- waavg_site2
waavg_dscr2$Site <- as.factor(waavg_dscr2$Site)

waavg_dscr2$Year <- waavg_yr2
waavg_dscr2$Year <- as.factor(waavg_dscr2$Year)

waavg_spscr2 <- as.data.frame(scores(waavg_nmds2, "species"))
waavg_spscr2$species <- rownames(waavg_spscr2)

#now graph
waavg_plot2 <- ggplot() +
  geom_text(data = waavg_spscr2, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = waavg_dscr2, aes(x = NMDS1, y = NMDS2, shape = Year, color = Site), size = 6.75, alpha = .8) +
  #ggtitle("Using Averages") +
  scale_color_manual(values = c("firebrick2", "gold", "darkorange",  "chartreuse3", "dodgerblue", "purple3"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

waavg_plot2

ggsave(file = "all_avg_wsn2.png", width = 10, height = 6)
```

idk what this is
```{r trying to get a nice facet wrap for all sites}
all_matr <- travg_wsn2

all_site <- all_matr$Site
all_matr$Site <- NULL

all_yr <- all_matr$Year
all_matr$Year <- NULL

all_nmds <- metaMDS(all_matr, trymax = 200)
all_nmds

all_dscr <- as.data.frame(scores(all_nmds)$sites)

all_dscr$Samp <- rownames(all_dscr)

all_dscr$Site <- all_site
all_dscr$Site <- as.factor(all_dscr$Site)

all_dscr$Year <- all_yr
all_dscr$Year <- as.factor(all_dscr$Year)

all_spscr <- as.data.frame(scores(all_nmds, "species"))
all_spscr$species <- rownames(all_spscr)

#graph
all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 3) +
  geom_point(data = all_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 4, alpha = .8) +
  #the colors I chose here were for a poster presentation and wanted to make sure I used color blind friendly colors.
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))+
  facet_wrap(~Site)

all_plot

ggsave(file = "final_nmds.png", height = 7.5, width = 15)
```

cannery row redux
```{r}
can_all <- all_dscr %>% 
  filter(Site == "Cannery Row")

can_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = can_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("Cannery Row")+
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

can_all_plot

ggsave(file = "can_nmds_wsn2.png", height = 6, width = 10)
```

cannery row
```{r}
can_mat <- travg_wsn2 %>% 
  filter(Site == "Cannery Row") %>% 
  select(-c(Site))

can_yr <- can_mat$Year
can_mat$Year <- NULL

can_nmds <- metaMDS(can_mat, trymax = 200)

can_dscr <- as.data.frame(scores(can_nmds)$sites)

can_dscr$Samp <- rownames(can_dscr)

can_dscr$Year <- can_yr
can_dscr$Year <- as.factor(can_dscr$Year)

can_spscr <- as.data.frame(scores(can_nmds, "species"))
can_spscr$species <- rownames(can_spscr)

#graph
can_plot <- ggplot() +
  geom_text(data = can_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = can_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

can_plot

#ggsave(file = "can_nmds_wsn.png", height = 6, width = 10)
```

carmel 
```{r}
car_mat <- travg_wsn2 %>% 
  filter(Site == "Carmel Point") %>% 
  select(-c(Site))

car_yr <- car_mat$Year
car_mat$Year <- NULL

car_nmds <- metaMDS(car_mat, trymax = 200)

car_dscr <- as.data.frame(scores(car_nmds)$sites)

car_dscr$Samp <- rownames(car_dscr)

car_dscr$Year <- car_yr
car_dscr$Year <- as.factor(car_dscr$Year)

car_spscr <- as.data.frame(scores(car_nmds, "species"))
car_spscr$species <- rownames(car_spscr)

#graph
car_plot <- ggplot() +
  geom_text(data = car_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = car_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

car_plot

#ggsave(file = "car_nmds_wsn.png", width = 10, height = 6)
```

carmel redux
```{r}
car_all <- all_dscr %>% 
  filter(Site == "Carmel Point")

car_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = car_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("Carmel") +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

car_all_plot

#ggsave(file = "car_nmds_wsn2.png", height = 6, width = 10)
```


pescadero point
```{r}
p_mat <- travg_wsn2 %>% 
  filter(Site == "Pescadero") %>% 
  select(-c(Site))

p_yr <- p_mat$Year
p_mat$Year <- NULL

p_nmds <- metaMDS(p_mat, trymax = 200)

p_dscr <- as.data.frame(scores(p_nmds)$sites)

p_dscr$Samp <- rownames(p_dscr)

p_dscr$Year <- p_yr
p_dscr$Year <- as.factor(p_dscr$Year)

p_spscr <- as.data.frame(scores(p_nmds, "species"))
p_spscr$species <- rownames(p_spscr)

#graph
p_plot <- ggplot() +
  geom_text(data = p_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = p_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

p_plot

#ggsave(file = "pesc_nmds_wsn.png", width = 10, height = 6)
```

pescadero redux
```{r}
p_all <- all_dscr %>% 
  filter(Site == "Pescadero")

p_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = p_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("Pescadero Point")+
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

p_all_plot

#ggsave(file = "pes_nmds_wsn2.png", width = 10, height = 6)
```


hopkins
```{r}
h_mat <- travg_wsn2 %>% 
  filter(Site == "Hopkins") %>% 
  select(-c(Site))

h_yr <- h_mat$Year
h_mat$Year <- NULL

h_nmds <- metaMDS(h_mat, trymax = 500)

h_dscr <- as.data.frame(scores(h_nmds)$sites)

h_dscr$Samp <- rownames(h_dscr)

h_dscr$Year <- h_yr
h_dscr$Year <- as.factor(h_dscr$Year)

h_spscr <- as.data.frame(scores(h_nmds, "species"))
h_spscr$species <- rownames(h_spscr)

#graph
h_plot <- ggplot() +
  geom_text(data = h_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = h_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

h_plot

#ggsave(file = "hopkins_nmds_wsn.png", width = 10, height = 6)
```

hopkins redux
```{r}
h_all <- all_dscr %>% 
  filter(Site == "Hopkins")

h_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = h_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("Hopkins")+
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

h_all_plot

#ggsave(file = "hopkins_nmds_wsn2.png", width = 10, height = 6)
```


point pinos
```{r}
pp_mat <- travg_wsn2 %>% 
  filter(Site == "Point Pinos") %>% 
  select(-c(Site))

pp_yr <- pp_mat$Year
pp_mat$Year <- NULL

pp_nmds <- metaMDS(pp_mat, trymax = 200)

pp_dscr <- as.data.frame(scores(pp_nmds)$sites)

pp_dscr$Samp <- rownames(pp_dscr)

pp_dscr$Year <- pp_yr
pp_dscr$Year <- as.factor(pp_dscr$Year)

pp_spscr <- as.data.frame(scores(pp_nmds, "species"))
pp_spscr$species <- rownames(pp_spscr)

#graph
pp_plot <- ggplot() +
  geom_text(data = pp_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = pp_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

pp_plot

#ggsave(file = "pointpinos_nmds_wsn.png", width = 10, height = 6)
```

pp redux
```{r}
pp_all <- all_dscr %>% 
  filter(Site == "Point Pinos")

pp_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = pp_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("Point Pinos")+
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

pp_all_plot

#ggsave(file = "pointpinos_nmds_wsn2.png", width = 10, height = 6)
```


china rock
```{r}
ch_mat <- travg_wsn2 %>% 
  filter(Site == "China Rock") %>% 
  select(-c(Site))

ch_yr <- ch_mat$Year
ch_mat$Year <- NULL

ch_nmds <- metaMDS(ch_mat, trymax = 200)

ch_dscr <- as.data.frame(scores(ch_nmds)$sites)

ch_dscr$Samp <- rownames(ch_dscr)

ch_dscr$Year <- ch_yr
ch_dscr$Year <- as.factor(ch_dscr$Year)

ch_spscr <- as.data.frame(scores(ch_nmds, "species"))
ch_spscr$species <- rownames(ch_spscr)

#graph
ch_plot <- ggplot() +
  geom_text(data = ch_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = ch_dscr, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  scale_shape_manual(values = c(18, 18, 19)) +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

ch_plot

#ggsave(file = "china_nmds_wsn.png", width = 10, height = 6)
```

china rock redux
```{r}
ch_all <- all_dscr %>% 
  filter(Site == "China Rock")

ch_all_plot <- ggplot() +
  geom_text(data = all_spscr, aes(x = NMDS1, y = NMDS2, label = species), alpha = 0.66, size = 4.5) +
  geom_point(data = ch_all, aes(x = NMDS1, y = NMDS2, shape = Year, color = Year), size = 6.75, alpha = .8) +
  ggtitle("China Rock") +
  scale_color_manual(values = c("#7ca1CC", "#0400dC", "#F05039"))+
  scale_shape_manual(values = c(18, 18, 19)) +
 theme_classic() +
  theme(legend.text = element_text(size = 15), legend.title =  element_text(size = 20), panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid"))

ch_all_plot

#ggsave(file = "china_nmds_wsn2.png", width = 10, height = 6)
```

```{r}
#ignore this lol
#trying a plot grid

nmds_grid <- plot_grid(can_all_plot + theme(legend.position = "none"),
                       car_all_plot + theme(legend.position = "none"),
                       ch_all_plot + theme(legend.position = "none"),
                       h_all_plot + theme(legend.position = "none"),
                       p_all_plot + theme(legend.position = "none"),
                       pp_all_plot + theme(legend.position = "none"),
                       ncol = 3)

nmds_grid

ggsave(file = "nmds_grid_final.png", height = 7.5, width = 15)
```

