---
title: "UrchinQuadPlots"
output: html_document
---


```{r install packages}
install.packages("lme4")
install.packages("tidyr")
install.packages("multcompView")
```

```{r library}
library(tidyverse)
library(tidyr)
library(lubridate)
library(vegan)
library(dplyr)
library(nlme)
library(lme4)
library(ggplot2)
library(datasets)
library(multcompView)
```

```{r data}

urchindata<-read.csv("UrchinDensity.csv")
algaldata<-read.csv("AlgalCover_2021.csv")
substratedata<-read.csv("Substrate_2021.csv")
```

```{r data checking for density}
str(urchindata)
unique(urchindata$Site)

##fix sites
urchindata <- urchindata %>%
  mutate(Site = replace(Site,Site == "Pecadero Point", "Pescadero Point")) %>%
  mutate(Site = replace(Site,Site == "Hopkins ", "Hopkins")) %>%
  mutate(Site = replace(Site,Site == "China Rock ", "China Rock"))
unique(urchindata$Site)



```




```{r graph for density}
urch_plot <- ggplot(urchindata, aes(x=Site, y=S_purpuratus, fill=Site)) + 
  geom_boxplot() +
  labs(x="Site", y="Urchin Density (ind./site)") + 
  theme_classic()

urch_plot
```



```{r graph w/ analysis}
urch_anova <- aov(S_purpuratus ~ Site, data = urchindata)

summary(urch_anova)

urch_tuk <- TukeyHSD(urch_anova)
urch_tuk

#compact letter display
cld <- multcompLetters4(urch_anova, urch_tuk)
print(cld)
#table with factors and 3rd quantile
Tk <- group_by(urchindata, Site) %>%
  summarise(mean=mean(S_purpuratus), quant=quantile(S_purpuratus, probs = 0.75)) %>% 
  arrange(desc(mean))
#extracting the compact letter display and adding to the Tk table 
cld <- as.data.frame.list(cld$Site)
Tk$cld <- cld$Letters
print(Tk)

#adding compact letter display from Tukey's test
ggplot(urchindata, aes(x=Site, y=S_purpuratus, fill=Site)) + 
  geom_boxplot() +
  labs(x="Site", y="Urchin Density (ind./site)") + 
  theme_classic() + 
  geom_text(data = Tk, aes(x=Site, y=quant, label=cld, size=3, vjust=-1, hjust=-0.5))

ggsave("urch_denplot.png", width=4, height=3, dpi=1000)
```

```{r}
## drop extras
str(algaldata)
colnames(algaldata)
algal_quad <- select(algaldata, -c("Investigators", "Entered.By", "Checked.By", "Notes", "Side"))
quad_long <- algal_quad %>%
  gather(key = "Category", value = "number", "Cr.NC":"Other")
```



```{r plot}

algalplot <- ggplot(quad_long, aes(x = Site, y = number, fill = Category)) +
  geom_boxplot() +
  theme_classic()

algalplot

#figure out whats weird here
quad_long_out <- quad_long |>
  filter(number > 150)
```

```{r vegan algal}
algal <- read.csv("Data/AlgalCover_2021.csv")

algal1 <- algal %>% 
  select(c("Site", "Cr.NC":"SG")) %>% 
  drop_na()
###delete row 91 because super outlier
algal1 <- algal1[-91,]

algal_matrix <- algal1

sites <- algal1$Site

algal_matrix$Site <- NULL

algal.mds <- metaMDS(algal_matrix, trymax=100)

algal.mds


### plot nMDS

data.scores <- as.data.frame(scores(algal.mds, "sites"))

data.scores$Samp <- rownames(data.scores)

data.scores$Site <- sites

head(data.scores)

species.scores <- as.data.frame(scores(algal.mds, "species"))

species.scores$species <- rownames(species.scores)

head(species.scores)




### make plot

algal_nMDS <-ggplot() + 
  geom_text(data=species.scores,aes(x=NMDS1,y=NMDS2,label=species),alpha=0.5) +  # add the species labels
  geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=Site),size=3) + # add the point markers
  #geom_text(data=data.scores,aes(x=NMDS1,y=NMDS2,label=Samp),size=6,vjust=0) +  # add the site labels
  scale_colour_manual(values=c("Point Pinos" = "red", "Cannery Row"  = "blue", "Sea Palm" = "pink", "Hopkins" = "green", "Carmel Point" = "purple", "Pescadero Point" = "black", "China Rock" = "grey" )) +
  coord_equal() +
  theme_classic()

algal_nMDS
```

```{r vegan substrate}
substrate <- read_csv("Data/Substrate_2021.csv")
str(substrate)
colnames(substrate)

substrate1 <- substrate %>% 
  select(c("Site", "Rock":"Sand")) %>% 
  drop_na()

substrate_matrix <- substrate1

sites <- substrate1$Site

substrate_matrix$Site <- NULL

substrate.mds <- metaMDS(substrate_matrix, trymax=200)

substrate.mds


### plot nMDS

data.scores <- as.data.frame(scores(substrate.mds, "sites"))

data.scores$Samp <- rownames(data.scores)

data.scores$Site <- sites

head(data.scores)

species.scores <- as.data.frame(scores(substrate.mds, "species"))

species.scores$species <- rownames(species.scores)

head(species.scores)




### make plot

substrate_nMDS <-ggplot() + 
  geom_text(data=species.scores,aes(x=NMDS1,y=NMDS2,label=species),alpha=0.5) +  # add the species labels
  geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=Site),size=3) + # add the point markers
  #geom_text(data=data.scores,aes(x=NMDS1,y=NMDS2,label=Samp),size=6,vjust=0) +  # add the site labels
  scale_colour_manual(values=c("Point Pinos" = "red", "Cannery Row"  = "blue", "Sea Palm" = "pink", "Hopkins" = "green", "Carmel Point" = "purple", "Pescadero Point" = "black", "China Rock" = "grey" )) +
  coord_equal() +
  theme_classic()

substrate_nMDS

```

```{r tidy data to join}

#### ALGAL DATA
# create % non foliose column
algal_quad$Tot_NF <- algal_quad$AC + algal_quad$Cr.NC + algal_quad$Cr.Cor + algal_quad$BR

algal_quad <- algal_quad %>% 
  mutate(Tot = select(., Cr.NC:Other) %>% 
           rowSums(na.rm=TRUE) )

## make a column go away

#algal_quad$Tot <- NULL

algal_quad$Per_NF <- (algal_quad$Tot_NF/algal_quad$Tot) * 100

# create key
algal_quad <- algal_quad %>% 
  mutate(Key = paste(Site, "_", Transect, "_", Quad.No) )

#### URCHIN DATA
# create quad size column
urchindata$Quad.Size <- 1

# create density column 
urchindata$Density <- urchindata$S_purpuratus/urchindata$Quad.Size

# create key
urchindata <- urchindata %>% 
  mutate(Key = paste(Site, "_", Transect.No, "_", Quad.No) )

#### SUBSTRATE DATA
# create sum column
substratedata <- substratedata %>% 
  mutate(Tot = select(., Rock:Sand) %>% 
           rowSums(na.rm=TRUE) )

# create % rocky
substratedata$Tot_Rock <- substratedata$Rock + substratedata$Boulder

substratedata$Per_Rock <- (substratedata$Tot_Rock/substratedata$Tot) * 100

# create key
substratedata <- substratedata %>% 
  mutate(Key = paste(Site, "_", Transect, "_", Quad.No) )

```


```{r join data}
test2 <- inner_join(urchindata, substratedata, by = "Key")
test3 <- inner_join(test2, algal_quad, by = "Key")

#Clean data
  temp = test3[ , c("Key", "Density", "Site.x", "Per_Rock", "Per_NF" ) ]
  write.csv( temp, "Data/UrchinModel.csv")
UrchinModel <- read.csv("Data/UrchinModel.csv")
```

```{r GLMM}
fit1 = glmer(Density ~  Per_Rock + Per_NF + ( 1 | Site.x ), data=UrchinModel, family=poisson)
```


```{r size frequency plots}
?gather()
urchindata_gather <- urchindata %>% gather("Size", "Count", 10:17)
head(urchindata_gather)
urchindata_gather$proportion <- urchindata_gather$Count / urchindata_gather$S_purpuratus

jpeg("urchin_count_constantscale.jpg", width = 6, height = 5, units = "in", res = 300)
ggplot(urchindata_gather, aes(Size, Count)) + 
  geom_boxplot() + facet_wrap(~Site) + 
  theme_bw() + xlab("Test diameter (cm)") + ylab(bquote('Urchins per m'^2)) + 
  scale_x_discrete(breaks=c("X..0.5.cm", "X..1.cm", "X1.cm", "X2.cm", "X3.cm", "X4.cm", "X5.cm", "X6.cm"),
                   labels=c("<0.5", "<1", "1-2", "2-3", "3-4", "4-5", "5-6", ">6")) + 
  theme(axis.text.x=element_text(size=8)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
dev.off()

jpeg("urchin_count_freescale.jpg", width = 6, height = 5, units = "in", res = 300)
ggplot(urchindata_gather, aes(Size, Count)) + 
  geom_boxplot() + facet_wrap(~Site, scale="free") + 
  theme_bw() + xlab("Test diameter (cm)") + ylab(bquote('Urchins per m'^2)) + 
  scale_x_discrete(breaks=c("X..0.5.cm", "X..1.cm", "X1.cm", "X2.cm", "X3.cm", "X4.cm", "X5.cm", "X6.cm"),
                   labels=c("<0.5", "<1", "1-2", "2-3", "3-4", "4-5", "5-6", ">6")) + 
  theme(axis.text.x=element_text(size=8)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
dev.off()

jpeg("urchin_proportion.jpg", width = 6, height = 5, units = "in", res = 300)
ggplot(urchindata_gather, aes(Size, proportion)) + 
  geom_boxplot() + facet_wrap(~Site) + 
  theme_bw() + xlab("Test diameter (cm)") + ylab(bquote('Proportion of Total')) + 
  scale_x_discrete(breaks=c("X..0.5.cm", "X..1.cm", "X1.cm", "X2.cm", "X3.cm", "X4.cm", "X5.cm", "X6.cm"),
                   labels=c("<0.5", "<1", "1-2", "2-3", "3-4", "4-5", "5-6", ">6")) + 
  theme(axis.text.x=element_text(size=8)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
dev.off()

jpeg("urchin_density.jpg", width = 6, height = 5, units = "in", res = 300)
ggplot(urchindata, aes(Site, S_purpuratus)) + 
  theme_classic() + geom_boxplot() + 
  ylab(bquote('Urchins per m'^2)) + 
  theme(axis.text.x=element_text(size = 7.5))
dev.off()

```


